export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const LOAD_PRODUCTS_COLORS = 'LOAD_PRODUCTS_COLORS'
export const LOAD_PRODUCTS_TYPES = 'LOAD_PRODUCTS_TYPES'
export const FILTER_PONIES = 'FILTER_PONIES'